### ISSUE TITLE
Ping interaction with ReactionThread

### ISSUE THREAD

**Issue by Salvi0** [MMPlugins/EmbedMessages#1]
As of now, when a thread is opened the ping for the specific emoji is included inside the embed description making it useless. I thought that meaby an interaction can be made between the 2 plugins to let the ping appear in the message outside of the embed.

**Comment by DarkView** [comment]
[Release 1.1](https://github.com/MMPlugins/EmbedMessages/releases/tag/1.1) fixes this by extracting any mentions from system messages into the non-embed message content.
Let me know here if you have any other issues!
