### ISSUE TITLE
how to change the author name to custom name?

### ISSUE THREAD

**Issue by thomas1329** [MMPlugins/EmbedMessages#2]
how to change in the modmail when I add the plugin to my system

**Comment by thomas1329** [comment]
![unknown11111](https://user-images.githubusercontent.com/82994801/129086445-63ef1e0a-086c-4f4c-a35c-8edc7909fe7d.png)

**Comment by DarkView** [comment]
All System messages have "System" as the embed author name.
What would you want to change it to?

**Comment by thomas1329** [comment]
hmm but the plugin will work in the modmail like in the support server they told that it cannot be changed i like to channged it to the name Freedom

**Comment by thomas1329** [comment]
If you can explain to me how to change it in the main modmail it will very help me

**Comment by DarkView** [comment]
New option `systemName` added in 488ba6a.

Learn how to use it [here](https://github.com/MMPlugins/EmbedMessages/blob/main/CONFIG.md)!
